import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import HomePage from "../components/HomePage";
import { Todos } from "../interfaces/types";
import Cookies from "js-cookie";

const Home: NextPage = () => {
  const [ssr, setSsr] = useState(true);

  const [todos, setTodos] = useState<Todos[]>(
    Cookies.get("todos") ? JSON.parse(Cookies.get("todos")) : []
  );
  return (
    <div className='todo_container '>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h3 className='todo_header'>My todolist app</h3>
      <HomePage todos={todos} setTodos={setTodos} />
    </div>
  );
};

export default Home;
