import type { NextPage } from "next";
import Head from "next/head";
import { SetStateAction, useState } from "react";
import HomePage from "../components/HomePage";
import { Todos } from "../interfaces/types";
import Cookies from "js-cookie";
import { getCookie, setCookie } from "typescript-cookie";
const Home: NextPage = () => {
  const [ssr, setSsr] = useState(true);
  let cookiesValue = Cookies.get("todos");
  const [todos, setTodos] = useState(
    cookiesValue ? JSON.parse(cookiesValue) : []
  );
  return (
    <div className='todo_container '>
      <Head>
        <title>Todo List App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h3 className='todo_header font-bold mt-4'>My todolist app</h3>
      <HomePage
        todos={todos}
        setTodos={setTodos}
        setEdit={function (value: SetStateAction<Boolean>): void {
          throw new Error("Function not implemented.");
        }}
        editTodo={{
          deadline: "",
          todo: "",
          id: "",
          bg: "",
        }}
      />
    </div>
  );
};

export default Home;
